#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scala-logging
Version  : 3.9.0
Release  : 1
URL      : https://github.com/lightbend/scala-logging/archive/v3.9.0.tar.gz
Source0  : https://github.com/lightbend/scala-logging/archive/v3.9.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/com/typesafe/scala-logging/scala-logging_2.12/3.9.0/scala-logging_2.12-3.9.0.jar
Source2  : https://repo.maven.apache.org/maven2/com/typesafe/scala-logging/scala-logging_2.12/3.9.0/scala-logging_2.12-3.9.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-scala-logging-data = %{version}-%{release}

%description
# scala-logging [![Build Status](https://travis-ci.org/lightbend/scala-logging.svg?branch=master)](https://travis-ci.org/lightbend/scala-logging)

%package data
Summary: data components for the mvn-scala-logging package.
Group: Data

%description data
data components for the mvn-scala-logging package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/typesafe/scala-logging/scala-logging_2.12/3.9.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/typesafe/scala-logging/scala-logging_2.12/3.9.0/scala-logging_2.12-3.9.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/typesafe/scala-logging/scala-logging_2.12/3.9.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/typesafe/scala-logging/scala-logging_2.12/3.9.0/scala-logging_2.12-3.9.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/typesafe/scala-logging/scala-logging_2.12/3.9.0/scala-logging_2.12-3.9.0.jar
/usr/share/java/.m2/repository/com/typesafe/scala-logging/scala-logging_2.12/3.9.0/scala-logging_2.12-3.9.0.pom
